## Business Applications for Python Assignment III
### Collections - Lists, Dictionaries, Tuples, and Sets

#### Problem 1
This problem is about list operations.  Look back at our notes and feel free to research how to perform the following operations.

a. Create an empty list.

b. Add string element "Monday" to the empty list.

c. Add string elements "Wednesday", "Thursday", "Thursday", "Friday", "Saturday", "Sunday", "Monday" into the list using one line of code.

d. Insert the element "Tuesday" at the appropriate location in the list so that the days of the week are in order.

e. Remove the last item in the list.

f. Remove the extra "Thursday" from the list. Print the result.

The expected output for problem 1 is
```
[]
['Monday']
['Monday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
```

In [ ]:
# Print the list in each part of the problem

def days():
    # a. Create an empty. Print the result.
    lst=[]
    print(lst)

    # b. Add string element "Monday" to list 'lst'.
    lst.append('Monday')
    print(lst)

    # c. Add string elements "Wednesday", "Thursday", "Thursday", "Friday", "Saturday", "Sunday", "Monday" into list 'lst' using one line of code. Print the result.
    lst.extend(['Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday'])
    print(lst)

    # d. Insert the element "Tuesday" at the appropriate location in the list so that the days of the week are in order. Print the result.
    lst.insert(1,'Tuesday')
    print(lst)

    # e. Remove the last item in the list. Print the result.
    lst.pop()
    print(lst)

    # f. Remove the extra "Thursday" from the list. Print the result.
    lst.remove('Thursday')
    print(lst)



Run the function with no argument

In [ ]:
# Run the function
days()

[]
['Monday']
['Monday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']


Expected Output
```
[]
['Monday']
['Monday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
```

#### Problem 2
This problem is designed to expand our understanding of dictionaries (called, 'objects', in other programming languages). Please demonstrate the following properties of and methods for dictionaries.

a. Show how to access the value for a specified key, use June for an example.

b. Create and print a list containing all of the keys for the dictionary shown below.

c. Create and print a list containing all of the values for the dictionary shown below.

d. Demonstrate a method to find how many items are in the dictionary.

e. Demonstrate a method to add a new key value pair, "December":31, to the dictionary.

Expected Output
```
30
['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November']
[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30]
11
{'January': 31, 'February': 28, 'March': 31, 'April': 30, 'May': 31, 'June': 30, 'July': 31, 'August': 31, 'September': 30, 'October': 31, 'November': 30, 'December': 31}
```

In [ ]:
def months_dict(dct):

    # a. Show how to access the value for a specified key, use June for an example. Print the result.
    dct['June']
    print(dct['June'])

    # b. Print all of the keys for the dictionary without using the .keys() method. Store the keys in a list. Print the result.
    k=[]
    for i in dct:
        k.append(i)
    print(k)


    # c. Print all of the values for the dictionary without using the .values() method. Store the values in a list. Print the result.
    v=[]
    for i in dct:
        v.append(dct[i])
    print(v)


    # d. Find how many items (key:value pairs) are in the dictionary. Print the result.
    print(len(dct))

    # e. Add a new key value pair, "December":31, to the dictionary. Print the result.
    dct['December']=31
    print(dct)


Run the function on some sample values.

In [ ]:
# Test data
months = {
    'January':31,
    'February':28,
    'March':31,
    'April':30,
    'May':31,
    'June':30,
    'July':31,
    'August':31,
    'September':30,
    'October': 31,
    'November':30,
}

# Run the function
months_dict(months)

30
['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November']
[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30]
11
{'January': 31, 'February': 28, 'March': 31, 'April': 30, 'May': 31, 'June': 30, 'July': 31, 'August': 31, 'September': 30, 'October': 31, 'November': 30, 'December': 31}


Expected Output
```
30
['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November']
[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30]
11
{'January': 31, 'February': 28, 'March': 31, 'April': 30, 'May': 31, 'June': 30, 'July': 31, 'August': 31, 'September': 30, 'October': 31, 'November': 30, 'December': 31}
```

#### Problem 3
This problems is about sets and their operations

a.  Create an empty set

b.  Create a set that contains values 1,2,3,4,5

c.  Add the value 6 to the set

d.  Add multiple values 7,8,9 to the set

e.  Remove the 6 from the set by referencing the value itself.

f. Use a comment to explain why it is not possible to discard the 3 from the set by referencing the index.


Expected output for problem 3
```
set() <class 'set'>
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 7, 8, 9}
```

In [ ]:
def set_operations():
    # a. Create an empty set, print the set and its data type
    s=set()
    print(s,type(s))

    # b. Create a set that contains values 1,2,3,4,5. Print the result.
    s={1,2,3,4,5}
    print(s)

    # c. Add the value 6 to the set. Print the result.
    s.add(6)
    print(s)

    # d. Add multiple values 7,8,9 using 1 command to the set. Print the result.
    s.update([7,8,9])
    print(s)

    # e. Remove the 6 from the set by referencing the value itself. Print the result.
    s.remove(6)
    print(s)

    # f. Write a comment to explain why it is not possible to discard the 3 from the set by referencing the index.
    # it is not possible to discard 3 from the set by referencing the index becuase 'indexing' cannot be applied to a 'set' in python.
    # Sets in pyhton are unordered and unindexed.

Run the function with no argument.

In [ ]:
# Run the function
set_operations()


set() <class 'set'>
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 7, 8, 9}


Expected Output
```
set() <class 'set'>
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 7, 8, 9}
```

#### Problem 4
Given the following collection of stock symbols, please perform the following:

a. Identify the symbol 'DPBE' using indexing. Expected output is
```
DPBE
```

b. Write a program to destructure the array so that the final result is:

```
['TEUCF', 'BBLKF', 'NMM', 'SAIA', 'SALT', 'SB', 'TK', 'NM', 'ERA', 'TCNAF', 'URAL', 'BRSWQ', 'DPBE', 'TOPS', 'GNKWF', 'AIRTW', 'SHIPW']
```
c.  Write a program to change all of the symbols to lowercase using the .lowere() method.
```
['teucf', 'bblkf', 'nmm', 'saia', 'salt', 'sb', 'tk', 'nm', 'era', 'tcnaf', 'ural', 'brswq', 'dpbe', 'tops', 'gnkwf', 'airtw', 'shipw']
```
Research a python function that can do this for you and cite your source.



In [24]:
def stock_calculations(lst):
    # a. Identify the symbol 'DPBE' using indexing. Print the result.
    print(lst[2][3])

    # b. program to destructure the array. Print the result.
    k=[]
    for i in lst:
        for j in i:
            k.append(j)
    print(k)

    # c. Change all of the symbols to lowercase using the .lower() method. Print the result.
    lowercase_lst = [symbol.lower() for symbol in k]
    print(lowercase_lst)


Run the function on some sample values.

In [25]:
stocks=[
        ['TEUCF', 'BBLKF', 'NMM', 'SAIA'],
        ['SALT','SB','TK','NM','ERA'],
        ['TCNAF','URAL','BRSWQ','DPBE'],
        ['TOPS','GNKWF','AIRTW','SHIPW'],
      ]

stock_calculations(stocks)

DPBE
['TEUCF', 'BBLKF', 'NMM', 'SAIA', 'SALT', 'SB', 'TK', 'NM', 'ERA', 'TCNAF', 'URAL', 'BRSWQ', 'DPBE', 'TOPS', 'GNKWF', 'AIRTW', 'SHIPW']
['teucf', 'bblkf', 'nmm', 'saia', 'salt', 'sb', 'tk', 'nm', 'era', 'tcnaf', 'ural', 'brswq', 'dpbe', 'tops', 'gnkwf', 'airtw', 'shipw']


Expected Output
```
DPBE
['TEUCF', 'BBLKF', 'NMM', 'SAIA', 'SALT', 'SB', 'TK', 'NM', 'ERA', 'TCNAF', 'URAL', 'BRSWQ', 'DPBE', 'TOPS', 'GNKWF', 'AIRTW', 'SHIPW']
['teucf', 'bblkf', 'nmm', 'saia', 'salt', 'sb', 'tk', 'nm', 'era', 'tcnaf', 'ural', 'brswq', 'dpbe', 'tops', 'gnkwf', 'airtw', 'shipw']
```

#### Problem 5
This data set shows a collection of high performing and low performing stocks.  Each stock symbol is associated with a percent change.  
```
stocks_d={
    'TEUCF':6352,
    'BBLKF':125,
    'NMM':57,
    .
    .
    .
```

Write a function to calculate the average increase and the average decrease in stock values. **Return** the result as a list. The expected output is
```
[757, -66]
```

In [15]:
def avg_stock(data):
    from numpy import mean

    increases = [value for value in data.values() if value > 0]
    decreases = [value for value in data.values() if value < 0]

    avg_increase = round(mean(increases)) if increases else 0
    avg_decrease = round(mean(decreases)) if decreases else 0

    return [avg_increase, avg_decrease]




Run the function on some sample values.

In [16]:
# Test data
sd={
    'TEUCF':6352,
    'BBLKF':125,
    'NMM':57,
    'SAIA':53,
    'SALT':48,
    'SB':46,
    'TK':45,
    'NM':44,
    'ERA':43,
    'TCNAF':-83,
    'URAL':-83,
    'BRSWQ':-80,
    'DPBE':-70,
    'TOPS':-59,
    'GNKWF':-53,
    'AIRTW':-51,
    'SHIPW':-46
         }

# Run the function
avg_stock(sd)

[757, -66]

Expected Output
```
[757, -66]
```

#### Problem 6
Write a program to perform set operations as prompted. After constructing the function, try it using the following sets as arguments,
```
a={1,2,3,4,5}
b={4,5,6,7,8}
```
use set methods to perform the following operations. Please see this [helpful resource explaining set operations](https://docs.python.org/2/library/sets.html).
a. Output the elements in a and b without repetitions. Expected output is    
```{1, 2, 3, 4, 5, 6, 7, 8}```

b. Output the values that are common to both sets. Expected output is    
```{4, 5}```

c.  Output the values in set **a** that do not appear in set **b**. Expected output is    
```{1, 2, 3}```

d.  Output the values in both sets without the common elements 4, 5. Expected output is    
```{1, 2, 3, 6, 7, 8}```.

In [ ]:
def partitioning_sets(s1, s2):

    # a. Output the elements in s1 and s2 without repetitions. Print the result.
    print(s1|s2)


    # b. Output the values that are common to both sets. Print the result.
    print(s1&s2)


    # c. Output the values in set s1 that do not appear in set s2. Print the result.
    print(s1-s2)


    # d. Output the values in both sets without the common elements 4, 5. Print the result.
    print(s1^s2)



Run the function on some sample values.

In [21]:
# Test data
a={1,2,3,4,5}
b={4,5,6,7,8}

# run the function
partitioning_sets(a, b)

NameError: name 'partitioning_sets' is not defined

Expected Output
```
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}
```

#### Problem 7
Let's say we have several observed values for the percent change for each of the stocks in the collection below.  

a.  Write a program that replaces the lists of values for each stock with the maximum value (```'TEUCF':[6352,6171,6053]``` would become ```'TEUCF': 6352```) for each stock and another program that does the same thing but for the minimum value. (use the .copy() method to make a copy of the dictionary)

Expected result for maximum values:
```
{'TEUCF': 6352, 'BBLKF': 125, 'NMM': 57, 'SAIA': 53, 'SALT': 49, 'SB': 46, 'TK': 45, 'NM': 44, 'ERA': 43, 'TCNAF': -81, 'URAL': -81, 'BRSWQ': -79, 'DPBE': 68, 'TOPS': -58, 'GNKWF': -52, 'AIRTW': -49, 'SHIPW': -40}
```
Expected result for minimum values:
```
{'TEUCF': 6053, 'BBLKF': 109, 'NMM': 50, 'SAIA': 50, 'SALT': 40, 'SB': 39, 'TK': 43, 'NM': 43, 'ERA': 42, 'TCNAF': -83, 'URAL': -83, 'BRSWQ': -81, 'DPBE': -70, 'TOPS': -59, 'GNKWF': -53, 'AIRTW': -51, 'SHIPW': -47}
```

b.  We would like to check which of these stocks, based on the three values, seems to be the most variable using the following formula: ```abs(pd=((max-min)/min)*100)```

If any of the stocks have a pd absolute value greater then 15, record the name of the stock in a list.  For example, for ```'SALT':[40,49,48]``` your program should determine that ```abs(((49-40)/40)*100) = 22.5```, and would add 'SALT' to your list. Expected output is
```
['SALT', 'SB', 'DPBE']
```

In [11]:
def stock_manipulations(d):

    # a. Finding max and min
    # Create a copy of the dictionary for min calculation
    d_copy = {}
    for key, value in d.items():
        d_copy[key] = value.copy()

    # a.i. Maximum of each list
    for i in d:
        d[i]=max(d[i])
    print(d)


    # a.ii. Minimum of each list
    for i in d_copy:
        d_copy[i]=min(d_copy[i])
    print(d_copy)

    # b. Percent difference
    variable_stocks = []
    for key, value in d.items():
        min_val = d_copy[key]
        pd = abs(((value - min_val) / min_val) * 100)
        if pd > 15:
            variable_stocks.append(key)
    print(variable_stocks)


    # a.i. Maximum of each list

    # a.ii. Minimum of each list



    # b. Percent difference




Run the function on some sample values.

In [12]:
# Test data
se={
    'TEUCF':[6352,6171,6053],
    'BBLKF':[109,125,111],
    'NMM':[52,50,57],
    'SAIA':[52,53,50],
    'SALT':[40,49,48],
    'SB':[39,46,46],
    'TK':[45,43,44],
    'NM':[44,44,43],
    'ERA':[43,42,43],
    'TCNAF':[-83,-81,-83],
    'URAL':[-83,-82,-81],
    'BRSWQ':[-80,-81,-79],
    'DPBE':[68,-70,67],
    'TOPS':[-59,-59,-58],
    'GNKWF':[-53,-52,-53],
    'AIRTW':[-51,-49,-50],
    'SHIPW':[-46,-40,-47]
         }

# Run the function
stock_manipulations(se)

{'TEUCF': 6352, 'BBLKF': 125, 'NMM': 57, 'SAIA': 53, 'SALT': 49, 'SB': 46, 'TK': 45, 'NM': 44, 'ERA': 43, 'TCNAF': -81, 'URAL': -81, 'BRSWQ': -79, 'DPBE': 68, 'TOPS': -58, 'GNKWF': -52, 'AIRTW': -49, 'SHIPW': -40}
{'TEUCF': 6053, 'BBLKF': 109, 'NMM': 50, 'SAIA': 50, 'SALT': 40, 'SB': 39, 'TK': 43, 'NM': 43, 'ERA': 42, 'TCNAF': -83, 'URAL': -83, 'BRSWQ': -81, 'DPBE': -70, 'TOPS': -59, 'GNKWF': -53, 'AIRTW': -51, 'SHIPW': -47}
['SALT', 'SB', 'DPBE']


Expected Output
```
{'TEUCF': 6352, 'BBLKF': 125, 'NMM': 57, 'SAIA': 53, 'SALT': 49, 'SB': 46, 'TK': 45, 'NM': 44, 'ERA': 43, 'TCNAF': -81, 'URAL': -81, 'BRSWQ': -79, 'DPBE': 68, 'TOPS': -58, 'GNKWF': -52, 'AIRTW': -49, 'SHIPW': -40}
{'TEUCF': 6053, 'BBLKF': 109, 'NMM': 50, 'SAIA': 50, 'SALT': 40, 'SB': 39, 'TK': 43, 'NM': 43, 'ERA': 42, 'TCNAF': -83, 'URAL': -83, 'BRSWQ': -81, 'DPBE': -70, 'TOPS': -59, 'GNKWF': -53, 'AIRTW': -51, 'SHIPW': -47}
['SALT', 'SB', 'DPBE']
```