# Instructions for Assignment 5
The following assignment relies heavily on the content covered in the week 5 notes.  Many of the operations you are asked to do here resemble those we went over in class.  Please make sure to reference lesson 5.1 and especially lesson 5.2 notes to guide you through these exercises.  You will need to examine the page:  https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl to understand the structure (tags, classes).  Note that for the sake of consistency, we will use the string version of the html content. This means we will NOT be running a get request to the URL and will not need to make use of the requests library.

#### Documentation
[beautifulsoup library](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)  

This assignment will rely on the following library.  You will need to import them again as part of your functions.

In [1]:
#Web scraping package
from bs4 import BeautifulSoup

### Problem 1
This problem is all about web-scraping with requests and BeautifulSoup. Parts a - d are missing a few steps. Take some time to fill in the blanks and understand the operations. Part e is left for you to complete and will ask you to combine the operations in parts a - d into one cohesive function.  

Use the following content to conduct the web-scraping exercises. Run this code block prior to completing the exercises.

In [2]:
content="""
<ul class="list list--kv list--col50">
                <li class="kv__item">
                    <small class="label">Open</small>
                    <span class="primary ">$144.03</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Day Range</small>
                    <span class="primary ">142.56 - 144.18</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">52 Week Range</small>
                    <span class="primary ">107.32 - 157.26</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Market Cap</small>
                    <span class="primary ">$2.37T</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Shares Outstanding</small>
                    <span class="primary ">17.34B</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Public Float</small>
                    <span class="primary ">16.51B</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Beta</small>
                    <span class="primary ">1.20</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Rev. per Employee</small>
                    <span class="primary ">$1.865M</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">P/E Ratio</small>
                    <span class="primary ">27.99</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">EPS</small>
                    <span class="primary ">$5.11</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Yield</small>
                    <span class="primary ">0.62%</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Dividend</small>
                    <span class="primary ">$0.22</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Ex-Dividend Date</small>
                    <span class="primary ">Aug 6, 2021</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Short Interest</small>
                    <span class="primary ">100.93M</span>
                    <span class="secondary ">09/15/21</span>
                </li>
                <li class="kv__item">
                    <small class="label">% of Float Shorted</small>
                    <span class="primary ">0.61%</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Average Volume</small>
                    <span class="primary ">80.12M</span>
                    <span class="secondary no-value"></span>
                </li>
        </ul>
"""

a.  Referencing the above response, create BeautifulSoup object called "results_page" parsed with 'html.parser'.

In [4]:
# build the BeautifulSoup object and name it results_page
results_page = BeautifulSoup(content,'html.parser')
print(type(results_page))

<class 'bs4.BeautifulSoup'>


**Expected Output**       
<class 'bs4.BeautifulSoup'>

b.  On the webpage:  https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl, look for the section called "Key Data".
![key_data](https://drive.google.com/uc?id=1ZMDc-Q000J5fksE28mMfyIJbFQHvlLUe)

 Inspect the page and verify that the tag/class combination that uniquely identifies each of the items in this table is 'li'/'kv__item'.  Find all elements identified by a tag of 'li' and a class_='kv__item'.  PLEASE NOTE THE **TWO** UNDERSCORES in kv__item.

In [5]:
# find all elements with the tag "li" and class_="kv__item"
key_data = results_page.find_all('li',class_="kv__item")
# print the data type for the kv_data object
print(type(key_data))

<class 'bs4.element.ResultSet'>


**Expected Output**   
<class 'bs4.element.ResultSet'>

c. The code to answer the above question should have returned a list.  Print the first item in this list.  You should get:
```
<li class="kv__item">
<small class="label">Open</small>
<span class="primary">$144.03</span>
<span class="secondary no-value"></span>
</li>
```

In [6]:
# print the first element in "key_data"
print(key_data[0])

<li class="kv__item">
<small class="label">Open</small>
<span class="primary">$144.03</span>
<span class="secondary no-value"></span>
</li>


**Expected Output**   
```
<li class="kv__item">
<small class="label">Open</small>
<span class="primary">$144.03</span>
<span class="secondary no-value"></span>
</li>
```

Extract the label "Open" and the value "$144.03"

![open_price](https://drive.google.com/uc?id=1OLQ3lVUd84dVytXft1K1GPffcb-ejbxq)

Note:  values may differ.

In [8]:
label=key_data[0].find('small', class_="label").get_text()
primary_val=key_data[0].find('span',class_="primary").get_text()
print(label)
print(primary_val)

Open
$144.03


**Expected Output**
```
Open
$144.03
```

d.  We need to be able to extract the text for each of the items in the key_data object.  Write a for loop to extract the label and primary value creating a list of the form [(label, value), (label,value),...]

In [10]:
kd_list=[]
for item in key_data:
    label=item.find('small', class_='label').get_text()
    value=item.find('span',class_="primary").get_text()
    kd_list.append((label,value))
print(kd_list)

[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]


**Expected Output**
```
[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]
```

e.  **BUILD THE FUNCTION Combine all of the above into a function that accepts html source code as an argument and returns the list of (label, value) pairs in the form** Please make sure to define and reference the function parameter so that your program will work correctly with multiple different inputs.
    
```
[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]
```.  

In [43]:
# Build the function here -- make sure to define a function parameter.
def get_key_data(html_source):
    from bs4 import BeautifulSoup
    results_page = BeautifulSoup(html_source,'html.parser')
    key_data = results_page.find_all('li',class_="kv__item")
    kd_list=[]
    for item in key_data:
        label=item.find('small', class_='label').get_text()
        value=item.find('span',class_="primary").get_text()
        kd_list.append((label,value))
    return kd_list


Run the function

In [44]:
aapl="""
<ul class="list list--kv list--col50">
                <li class="kv__item">
                    <small class="label">Open</small>
                    <span class="primary ">$144.03</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Day Range</small>
                    <span class="primary ">142.56 - 144.18</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">52 Week Range</small>
                    <span class="primary ">107.32 - 157.26</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Market Cap</small>
                    <span class="primary ">$2.37T</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Shares Outstanding</small>
                    <span class="primary ">17.34B</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Public Float</small>
                    <span class="primary ">16.51B</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Beta</small>
                    <span class="primary ">1.20</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Rev. per Employee</small>
                    <span class="primary ">$1.865M</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">P/E Ratio</small>
                    <span class="primary ">27.99</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">EPS</small>
                    <span class="primary ">$5.11</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Yield</small>
                    <span class="primary ">0.62%</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Dividend</small>
                    <span class="primary ">$0.22</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Ex-Dividend Date</small>
                    <span class="primary ">Aug 6, 2021</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Short Interest</small>
                    <span class="primary ">100.93M</span>
                    <span class="secondary ">09/15/21</span>
                </li>
                <li class="kv__item">
                    <small class="label">% of Float Shorted</small>
                    <span class="primary ">0.61%</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Average Volume</small>
                    <span class="primary ">80.12M</span>
                    <span class="secondary no-value"></span>
                </li>
        </ul>
"""

In [45]:
results_a = get_key_data(aapl)
print(results_a)

[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]


Expected Output
```
[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]
```

In [46]:
goog="""
<ul class="list list--kv list--col50">
                <li class="kv__item">
                    <small class="label">Open</small>
                    <span class="primary ">$2,798.12</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Day Range</small>
                    <span class="primary ">2,788.59 - 2,806.34</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">52 Week Range</small>
                    <span class="primary ">1,489.45 - 2,936.41</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Market Cap</small>
                    <span class="primary ">$1.86T</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Shares Outstanding</small>
                    <span class="primary ">320.17M</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Public Float</small>
                    <span class="primary ">279.85M</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Beta</small>
                    <span class="primary ">1.08</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Rev. per Employee</small>
                    <span class="primary ">$1.348M</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">P/E Ratio</small>
                    <span class="primary ">30.39</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">EPS</small>
                    <span class="primary ">$92.24</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Yield</small>
                    <span class="primary is-na">N/A</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Dividend</small>
                    <span class="primary is-na">N/A</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Ex-Dividend Date</small>
                    <span class="primary is-na">N/A</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Short Interest</small>
                    <span class="primary ">2.64M</span>
                    <span class="secondary ">09/15/21</span>
                </li>
                <li class="kv__item">
                    <small class="label">% of Float Shorted</small>
                    <span class="primary ">0.94%</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Average Volume</small>
                    <span class="primary ">1.05M</span>
                    <span class="secondary no-value"></span>
                </li>
        </ul>
"""

In [47]:
results_g = get_key_data(goog)
print(results_g)

[('Open', '$2,798.12'), ('Day Range', '2,788.59 - 2,806.34'), ('52 Week Range', '1,489.45 - 2,936.41'), ('Market Cap', '$1.86T'), ('Shares Outstanding', '320.17M'), ('Public Float', '279.85M'), ('Beta', '1.08'), ('Rev. per Employee', '$1.348M'), ('P/E Ratio', '30.39'), ('EPS', '$92.24'), ('Yield', 'N/A'), ('Dividend', 'N/A'), ('Ex-Dividend Date', 'N/A'), ('Short Interest', '2.64M'), ('% of Float Shorted', '0.94%'), ('Average Volume', '1.05M')]


Expected Output
```
[('Open', '$2,798.12'), ('Day Range', '2,788.59 - 2,806.34'), ('52 Week Range', '1,489.45 - 2,936.41'), ('Market Cap', '$1.86T'), ('Shares Outstanding', '320.17M'), ('Public Float', '279.85M'), ('Beta', '1.08'), ('Rev. per Employee', '$1.348M'), ('P/E Ratio', '30.39'), ('EPS', '$92.24'), ('Yield', 'N/A'), ('Dividend', 'N/A'), ('Ex-Dividend Date', 'N/A'), ('Short Interest', '2.64M'), ('% of Float Shorted', '0.94%'), ('Average Volume', '1.05M')]
```

In [48]:
msft="""
<ul class="list list--kv list--col50">
                <li class="kv__item">
                    <small class="label">Open</small>
                    <span class="primary ">$296.22</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Day Range</small>
                    <span class="primary ">293.76 - 296.64</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">52 Week Range</small>
                    <span class="primary ">199.62 - 305.84</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Market Cap</small>
                    <span class="primary ">$2.22T</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Shares Outstanding</small>
                    <span class="primary ">7.51B</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Public Float</small>
                    <span class="primary ">7.4B</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Beta</small>
                    <span class="primary ">1.19</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Rev. per Employee</small>
                    <span class="primary ">$928.66K</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">P/E Ratio</small>
                    <span class="primary ">36.48</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">EPS</small>
                    <span class="primary ">$8.06</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Yield</small>
                    <span class="primary ">0.84%</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Dividend</small>
                    <span class="primary ">$0.62</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Ex-Dividend Date</small>
                    <span class="primary ">Nov 17, 2021</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Short Interest</small>
                    <span class="primary ">44.2M</span>
                    <span class="secondary ">09/15/21</span>
                </li>
                <li class="kv__item">
                    <small class="label">% of Float Shorted</small>
                    <span class="primary ">0.60%</span>
                    <span class="secondary no-value"></span>
                </li>
                <li class="kv__item">
                    <small class="label">Average Volume</small>
                    <span class="primary ">22.76M</span>
                    <span class="secondary no-value"></span>
                </li>
        </ul>
"""

In [49]:
results_m = get_key_data(msft)
print(results_m)

[('Open', '$296.22'), ('Day Range', '293.76 - 296.64'), ('52 Week Range', '199.62 - 305.84'), ('Market Cap', '$2.22T'), ('Shares Outstanding', '7.51B'), ('Public Float', '7.4B'), ('Beta', '1.19'), ('Rev. per Employee', '$928.66K'), ('P/E Ratio', '36.48'), ('EPS', '$8.06'), ('Yield', '0.84%'), ('Dividend', '$0.62'), ('Ex-Dividend Date', 'Nov 17, 2021'), ('Short Interest', '44.2M'), ('% of Float Shorted', '0.60%'), ('Average Volume', '22.76M')]


Expected Output
```
[('Open', '$296.22'), ('Day Range', '293.76 - 296.64'), ('52 Week Range', '199.62 - 305.84'), ('Market Cap', '$2.22T'), ('Shares Outstanding', '7.51B'), ('Public Float', '7.4B'), ('Beta', '1.19'), ('Rev. per Employee', '$928.66K'), ('P/E Ratio', '36.48'), ('EPS', '$8.06'), ('Yield', '0.84%'), ('Dividend', '$0.62'), ('Ex-Dividend Date', 'Nov 17, 2021'), ('Short Interest', '44.2M'), ('% of Float Shorted', '0.60%'), ('Average Volume', '22.76M')]
```